# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmdEdit < Formula
  desc "Editor wrapper that exports project context to the child editor and ships shell completions"
  homepage "https://github.com/jlrickert/cmd-edit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/cmd-edit/releases/download/v0.1.0/ed_0.1.0_darwin_amd64.tar.gz"
      sha256 "ee2109f31578f1975d5663cdca2b136e0a1c4e637ff7326170024f648e866419"

      define_method(:install) do
        bin.install "ed"
        generate_completions_from_executable(bin/"ed", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/cmd-edit/releases/download/v0.1.0/ed_0.1.0_darwin_arm64.tar.gz"
      sha256 "0faa5dcad1e961dff97cef9d8f7c601e80e1d7b0f3fdb83291bb66e2c623b8d5"

      define_method(:install) do
        bin.install "ed"
        generate_completions_from_executable(bin/"ed", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/cmd-edit/releases/download/v0.1.0/ed_0.1.0_linux_amd64.tar.gz"
      sha256 "b52880852868d6b5cae2a5a8d3596495ffda19a39f98881398b4022588b5e675"
      define_method(:install) do
        bin.install "ed"
        generate_completions_from_executable(bin/"ed", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/cmd-edit/releases/download/v0.1.0/ed_0.1.0_linux_arm64.tar.gz"
      sha256 "34a84119c70a327dae6bd256aaac5376c2fdb397d98eadbe22c23311912577c5"
      define_method(:install) do
        bin.install "ed"
        generate_completions_from_executable(bin/"ed", "completion")
      end
    end
  end

  test do
    system "#{bin}/ed", "--version"
  end
end
