# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "A brew-style dotfile package manager with taps, profiles, overlays, and cross-platform support"
  homepage "https://github.com/jlrickert/dots"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.0/dots_0.2.0_darwin_amd64.tar.gz"
      sha256 "3ce7526bf5c40989e85d0d926c187a855598591a3ec33e91b1c6c89e821571db"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.0/dots_0.2.0_darwin_arm64.tar.gz"
      sha256 "19c750e6c732f31a8b4f8a8e22def77e9d902c05ef1f5c6fe19bac52883f33bc"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.0/dots_0.2.0_linux_amd64.tar.gz"
      sha256 "7b45a5c9c83d1b4416070288d5d732a87d59cd6df5d6d53288e91d5d36ea6cb7"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.0/dots_0.2.0_linux_arm64.tar.gz"
      sha256 "efcc2485daf6f14e2046884b10655e2ce57ba83911620c6afa44261ee8a6aa05"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  test do
    system "#{bin}/dots", "--version"
  end
end
