# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "A brew-style dotfile package manager with taps, profiles, overlays, and cross-platform support"
  homepage "https://github.com/jlrickert/dots"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.1/dots_0.2.1_darwin_amd64.tar.gz"
      sha256 "678e3e72ca98d836db42635a77491872350d78fde2db5c2ec66ac399180db2d3"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.1/dots_0.2.1_darwin_arm64.tar.gz"
      sha256 "d5fb34059cb3ca38d3af63ac52ce26cbe4d302f642faf63933ec40eabade8c9f"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.1/dots_0.2.1_linux_amd64.tar.gz"
      sha256 "617f94cbb5884ee4525ecf7952425d7879468623b3fe7a69a155b90e2025ef6b"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.2.1/dots_0.2.1_linux_arm64.tar.gz"
      sha256 "37625a723534490b065eaf2feba844d8477dd2ef7921e7feff14e5d169734363"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  test do
    system "#{bin}/dots", "--version"
  end
end
