# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "A brew-style dotfile package manager with taps, profiles, overlays, and cross-platform support"
  homepage "https://github.com/jlrickert/dots"
  version "0.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/dots/releases/download/v0.8.1/dots_0.8.1_darwin_amd64.tar.gz"
      sha256 "cf43d2d0842027c72d01589d7a5381f587f8474e4927c650429201146d3aefd4"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/dots/releases/download/v0.8.1/dots_0.8.1_darwin_arm64.tar.gz"
      sha256 "64301dcd18c85f9a6639c7f0fbe2a967e619076a4b5334b3f41efb1875d6856d"

      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.8.1/dots_0.8.1_linux_amd64.tar.gz"
      sha256 "2cf4dfe85d11367be2d05c4542789dea2dc13771640b5efa64768604ffa874b0"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/dots/releases/download/v0.8.1/dots_0.8.1_linux_arm64.tar.gz"
      sha256 "b412eb60897cea9862dbf87d5f4b6f7494bb1af504f6d90682a380ae978f0f20"
      define_method(:install) do
        bin.install "dots"
        generate_completions_from_executable(bin/"dots", "completion")
      end
    end
  end

  test do
    system "#{bin}/dots", "--version"
  end
end
