# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keg < Formula
  desc "Project-focused KEG CLI with pruned command surface"
  homepage "https://github.com/jlrickert/tapper"
  version "0.24.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/tapper/releases/download/v0.24.0/keg_0.24.0_darwin_amd64.tar.gz"
      sha256 "351d9331ba9f1ab6b34ada58452599e9974e7ed086d2a36e35be9cd51561d8d3"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/tapper/releases/download/v0.24.0/keg_0.24.0_darwin_arm64.tar.gz"
      sha256 "74818fbb94bd000df641103dd8bf526da770116ec9e48966bcc01b9bf2ff12e3"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.24.0/keg_0.24.0_linux_amd64.tar.gz"
      sha256 "97ae31ccd11a44c9374df27223f96dc8f25671319adbb1cce3fdabff368cf7ae"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.24.0/keg_0.24.0_linux_arm64.tar.gz"
      sha256 "7d0a33f234a7b70404fb9ac8e0288f66a50bbdcd99ea09cb076e7049a6c99de4"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  test do
    system "#{bin}/keg", "--version"
  end
end
