# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keg < Formula
  desc "Project-focused KEG CLI with pruned command surface"
  homepage "https://github.com/jlrickert/tapper"
  version "0.18.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/tapper/releases/download/v0.18.1/keg_0.18.1_darwin_amd64.tar.gz"
      sha256 "70a4056fbfd284da0ce6696bb4b3023b87a82c896cac944279ff445a27883d34"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/tapper/releases/download/v0.18.1/keg_0.18.1_darwin_arm64.tar.gz"
      sha256 "df3d9d9d064e8a50f96d418b6056c04648514f0e3a0dd5e01531aadf3f42abeb"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.18.1/keg_0.18.1_linux_amd64.tar.gz"
      sha256 "7994b5f8c48643e31f395375e0fb1c70162f7fa020cf4065b63a71c4eed0172e"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.18.1/keg_0.18.1_linux_arm64.tar.gz"
      sha256 "2ec43f34ddb36263498e2fce46ae5f5205d6f001b9d4f1828dc30520f31189f4"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  test do
    system "#{bin}/keg", "--version"
  end
end
