# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keg < Formula
  desc "Project-focused KEG CLI with pruned command surface"
  homepage "https://github.com/jlrickert/tapper"
  version "0.20.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/tapper/releases/download/v0.20.0/keg_0.20.0_darwin_amd64.tar.gz"
      sha256 "534ecc61c18d099f967097e76068f85b0618f5f32feee39c3c90a647589c18cf"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/tapper/releases/download/v0.20.0/keg_0.20.0_darwin_arm64.tar.gz"
      sha256 "a78b0c33fc4b1b039a08f65a0c42afd0eb62b53a7c90d1e97e4aa18940e51d49"

      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.20.0/keg_0.20.0_linux_amd64.tar.gz"
      sha256 "1d3818dcca5707ac1a61acf766d92c8db790689b29e381a0a713239b01778e39"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.20.0/keg_0.20.0_linux_arm64.tar.gz"
      sha256 "937653ddc683e86dd2d4cbbf7ff1eb47dc4790f2b21c552d8a3dac13f89a06cf"
      define_method(:install) do
        bin.install "keg"
        generate_completions_from_executable(bin/"keg", "completion")
      end
    end
  end

  test do
    system "#{bin}/keg", "--version"
  end
end
