# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapper < Formula
  desc "CLI toolset for managing KEGs (Knowledge Exchange Graphs)"
  homepage "https://github.com/jlrickert/tapper"
  version "0.41.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/tapper/releases/download/v0.41.0/tap_0.41.0_darwin_amd64.tar.gz"
      sha256 "e27820cd2424871109ed73a2dbfbc02b13893d2a2d91f341fbdaf75edb317aaa"

      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/tapper/releases/download/v0.41.0/tap_0.41.0_darwin_arm64.tar.gz"
      sha256 "67c32df9c192aa10e027ee2e9dfdd7310dea53f0779ca90356afd85d86f1ea53"

      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.41.0/tap_0.41.0_linux_amd64.tar.gz"
      sha256 "0075b71b4c5062bbfc366ed223cabd9c4424e13dc17a10080a84138c4ec35c7a"
      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.41.0/tap_0.41.0_linux_arm64.tar.gz"
      sha256 "1f20a85d89dc9930c853e0d88f1548875c64a7e73de0612a0d7ebc0c668acf1b"
      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
  end

  test do
    system "#{bin}/tap", "--version"
  end
end
