# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapper < Formula
  desc "CLI toolset for managing KEGs (Knowledge Exchange Graphs)"
  homepage "https://github.com/jlrickert/tapper"
  version "0.27.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jlrickert/tapper/releases/download/v0.27.0/tap_0.27.0_darwin_amd64.tar.gz"
      sha256 "75aceae0f4a2502ca154d3eddce8d590c00f0293379cc43fc382670c44a49a69"

      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jlrickert/tapper/releases/download/v0.27.0/tap_0.27.0_darwin_arm64.tar.gz"
      sha256 "c5a81cc24491eddc22769779258ce02c2b1d22c613c1f3bba7c201aa98dc7308"

      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.27.0/tap_0.27.0_linux_amd64.tar.gz"
      sha256 "4b8bb29b19ec63118dc1d988d0db04d218cce55028764dd144ffbb2a7d127432"
      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jlrickert/tapper/releases/download/v0.27.0/tap_0.27.0_linux_arm64.tar.gz"
      sha256 "031e7193cd92c6315c8062b9a99fbe546aef9c891f9dd987fec20f0db5959608"
      define_method(:install) do
        bin.install "tap"
        generate_completions_from_executable(bin/"tap", "completion")
      end
    end
  end

  test do
    system "#{bin}/tap", "--version"
  end
end
